name: Stable release 🕊️📦

on:
  release:
    types:
      - released
      - prereleased

jobs:
  docker:
    name: Build frontend Docker images 💿💻
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.1
        with:
          show-progress: false

      - name: Configure QEMU ⚙️
        uses: docker/setup-qemu-action@v3.0.0

      - name: Configure Docker Buildx ⚙️
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to Docker Hub 🔑
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry 🔑
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.JF_BOT_TOKEN }}

      - name: Build and push stable images 🛠️⬆️
        if: github.event.action == 'released'
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: packaging/docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm
          build-args: |
            IS_STABLE=1
          tags: |
            jellyfin/jellyfin-vue:stable
            jellyfin/jellyfin-vue:stable.${{ github.event.release.tag_name }}
            jellyfin/jellyfin-vue:latest
            ghcr.io/jellyfin/jellyfin-vue:stable
            ghcr.io/jellyfin/jellyfin-vue:stable.${{ github.event.release.tag_name }}
            ghcr.io/jellyfin/jellyfin-vue:latest

      - name: Build and push release candidate images 🛠️⬆️
        if: github.event.action == 'prereleased'
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: packaging/docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm
          build-args: |
            IS_STABLE=1
          tags: |
            jellyfin/jellyfin-vue:stable-rc
            jellyfin/jellyfin-vue:stable-rc.${{ github.event.release.tag_name }}
            ghcr.io/jellyfin/jellyfin-vue:stable-rc
            ghcr.io/jellyfin/jellyfin-vue:stable-rc.${{ github.event.release.tag_name }}

  tauri:
    name: Build Tauri 🛠️
    strategy:
      fail-fast: false
      matrix:
        platform:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
    defaults:
      run:
        working-directory: packaging/tauri

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.1
        with:
          show-progress: false

      - name: Setup node environment ⚙️
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
          check-latest: true

      - name: Install npm dependencies 📦
        run: npm ci --no-audit

      - name: Install Linux dependencies 📦🐧
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update -qq
          sudo apt install -y --no-install-recommends $(cat apt_packages)

      - name: Build Tauri 🛠️
        run: npm run build

      - name: Upload artifact (Linux) ⬆️🐧
        uses: actions/upload-artifact@v3.1.3
        if: matrix.platform == 'ubuntu-latest'
        with:
          name: jellyfin-vue_linux-amd64
          path: |
            packaging/tauri/target/release/bundle/deb/*.deb
            packaging/tauri/target/release/bundle/appimage_deb

      - name: Upload artifact (MacOS) ⬆️🍎
        uses: actions/upload-artifact@v3.1.3
        if: matrix.platform == 'macos-latest'
        with:
          name: jellyfin-vue_macOS
          path: |
            packaging/tauri/target/release/bundle/macos
            packaging/tauri/target/release/bundle/dmg/*.dmg

      - name: Upload artifact (Windows) ⬆️🪟
        uses: actions/upload-artifact@v3.1.3
        if: matrix.platform == 'windows-latest'
        with:
          name: jellyfin-vue_windows_amd64
          path: packaging/tauri/target/release/jellyfin-vue.exe
